# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Coding Imp
email: mitchell@schwitzer.ca
description: > # this means to ignore newlines until "baseurl:"
  All the muck that's fit to rake!<br/>
  <br/>
  I'm a software engineer always looking to learn and improve my abilities. As of now, I work primarily in Scala.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://schwitzerm.gitlab.io/" # the base hostname & protocol for your site
author: "Mitchell Schwitzer"
twitter_username: "meschwitzer"
github_username: "schwitzerm"

# Build settings
markdown: kramdown
