# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mitchell's... Stuff
email: mitchell@schwitzer.ca
description: > # this means to ignore newlines until "baseurl:"
  All the muck that's fit to rake!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://schwitzerm.github.io/" # the base hostname & protocol for your site
twitter_username: meschwitzer
github_username:  schwitzerm

# Build settings
markdown: kramdown
